### ISSUE TITLE
More units support

### ISSUE THREAD

**Issue by librehat** [librehat/com.librehat.yahooweather#16]
The new API returns wrong wind.chill (Feels like temperature) for Celsius. It's also nice for us to convert pressure, visibility, etc into different units independently.

Hence, the solution may be getting Fahrenheit temperature (along with distance in miles and so on) from Yahoo! and then do all the conversion ourselves in code. It also means more options in unit configuration!

**Comment by smitgd** [comment]
Hi Symeon,
Yes, there seems to be "wrong" data returned with either units F or C!. Previously, even with the "original" api you used, when F is selected, the wind speed displayed was in km/h but the actual value returned was in mph (mi/h or miles per hours). This also occurs with the new api. However, this was the only problem I saw with using the original API (not really a problem with the API).

However, there seem to be several problems with the "new" api in both F and C units.

With F selected: pressure is in mb (e.g., 951.0) instead of inches (28.08). Wind speed and visibility are in km/s and km instead of mi/h and miles (must multiply by 0.621371 to convert). Temperature and chill are in F as expected and are OK.

With C selected: pressure is weird and very large (i.e., 32204.57). Wind speed is also large 17.70 -- should be 7mph or about 11km/h. As you pointed out, "chill" seems to be in degrees F instead of C. Visibility is too large (25.91 instead of the correct 16km).

I agree that the data returned in units F are at least (currently) consistent, unlike the weird C values. However, if yahoo corrects these "bugs" it will break the code again if F is used as the basis for conversions. The "old" api with a different URL also (currently) works without oauth and returns consistent and reasonable data for both C and F. 

However, not sure how long the current yahoo URLs  and APIs will continue to work without oauth?
-gene
P/S: I don't see that you have added oauth anywhere in the code, but I could be wrong; this is the first time I have looked at this type of code. :)

**Comment by librehat** [comment]
Weather API is OAuth1, they don't require for secret and key. The old API with different URL no longer works (server not found for that domain).

I mentioned this bug on Twitter to ydn, but there is no update so far.

**Comment by smitgd** [comment]
I get a good response with this url:
curl "http://xml.weather.yahoo.com/forecastrss?w=2472005&u=c"
Is this what you mean by "old API with different URL"? When I use this url in your code before you made any recent changes, it also worked. Maybe it doesn't work at your location?
-gene

**Comment by librehat** [comment]
Yeah. Strangely it didn't work the other day I tested...

Anyway, we're using JSON now... And this URL is undocumented.

**Comment by smitgd** [comment]
Looks like lots at yahoo is now undocumented. Always get "internal error" or "engineers working on the problem" when I go to developer links.

Don't know if your "kde4" branch is still active but I see that you made a change on Apr 2 (and still using XML and not JSON). I no longer have KDE4 installed but, using curl, the url in branch kde4 Yahoo.qml doesn't work, i.e.,
curl "http://xml.weather.yahooapis.com/forecastrss?w=2472005&u=c"
curl: (6) Could not resolve host: xml.weather.yahooapis.com
but
curl "http://xml.weather.yahoo.com/forecastrss?w=2472005&u=c"
is OK. 
The only difference is "apis" is removed from "yahooapis".
-gene

**Comment by librehat** [comment]
Just updated `kde4` branch. I don't have KDE4 installed anymore so no longer wish to maintain `kde4` branch. As for Plasma 5 (`master`), we should focus on new API now since it's the only way to get JSON format data. And hopefully engineers at Yahoo! can address those outstanding issues soon.
