### ISSUE TITLE
Few issues with units

### ISSUE THREAD

**Issue by pejakm** [librehat/com.librehat.yahooweather#20]
- [x] readability issue: you should use empty space between number and unit - `16 km` instead of `16km`
- [x] label for pascal is `Pa`, not `pa`
- [x] you should really use hectopascals instead of pascals (or add hectopascals), it's more human readable (1 hPa = 100 Pa, eg. 101325 Pa = 1013,25 hPa)
- [x] in some countries (Bosnia and Herzegovina, Montenegro, Serbia, etc.) it is more custom to use millibars instead of pascals (1 mbar = 1 hPa = 100 Pa, eg. 101325 Pa = 1013,25 mbar = 1013,25 hPa), but adding just hectopascals should suffice (they'll figure out it's the same)
- [ ] possibility of using 24-hour time for sunrise and sunset would be nice :)

I can do all of these (not sure anout the last one, though), so let me know if you agree with suggestions, I'll make a PR later. :)

**Comment by librehat** [comment]
1. If we do the first one, we have to ensure we do it for all texts (make sure double check that).
2. Yes, please change it to `Pa`.
3. I prefer changing to `hPa` since `Pa` is less likely used in this situation.
4. Adding another unit option for `millibars` may be preferable.
5. Then we need to do the conversion. I personally don't really mind 12-hr or 24-hr time. But if you do, please make it optional.

**Comment by pejakm** [comment]
Okay, thanks for input. I'll make a PR in the next day or two. (I'll do a feature by feature so you can easily review all.)

**Comment by librehat** [comment]
Thank you

**Comment by pejakm** [comment]
There are still issues with displaying certain units. I figured out what the problems are and fixed them all. PR pending.

**Comment by librehat** [comment]
24-hr is added by ec23a23bca5b662b7190b882349dbb4f31ce3266
