### ISSUE TITLE
[Bug] Some widget value is different than the Yahoo! Weather page value

### ISSUE THREAD

**Issue by kikadf** [librehat/com.librehat.yahooweather#35]
Hi!

I use 811659 WOEID, and when I control the value of widget with the Yahoo! Weather page, I look that some value is different in same time.

The temparature now: 16 C in widget, 19 C on webpage
Wind: 6 km/h in widget, 7 km/h on webpage
UV: 0 in widget (always), 1 on webpage

I use the last git version.

**Comment by smitgd** [comment]
I see discrepancies too but mostly for current temp. and "feels like" temperature (wind, humidity, pressure usually OK). However, except for UV Index, the widget is displaying the same information contained in the yahoo query response.  I think this is because there is a "lag" in the widget current temperature compared to the yahoo web page and the yahoo phone app. The data in the widget seems to be about 1 hour behind the yahoo web page/app. Not sure what can be done to fix this. 

I tried to look at how the web page accesses the data but it is encrypted via https. Even after "decrypting" with wireshark, the data is still compressed so was still not able to see anything useful as to how the app or webpage actually access the data. Not even sure if this is possible (or useful).

Also, the widget seems to be using the pressure "steady/rising/falling" values (0-2) for UV Index so it is completely wrong. (Currently with bright sun, widget says UV index is 0 but app/webpage says UV is 8--very high).

**Comment by librehat** [comment]
Yahoo! probably is using their private API on their own products (which is also reasonable). 

This is not a bug of this widget..

**Comment by smitgd** [comment]
Except for UV?

**Comment by librehat** [comment]
You're right, the UV index seems always wrong (don't remember why I put it there)
